# IP addresses, port numbers, and calibration values
host_y: "192.168.1.10"    # IP address for host_x
host_x: "192.168.0.11"    # IP address for host_y
port: 10001               # Port number
cal_x: 0.0878657411       # Calibration value for host_x
cal_y: 0.0650956907       # Calibration value for host_y

